name: LeBron Stat Bot

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every hour (UTC)

jobs:
  post-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install tweepy nba-api

      - name: Download last_tweet_date artifact
        uses: actions/download-artifact@v3
        with:
          name: last_tweet_date
          path: ./

      - name: Run LeBron Stat Bot
        env:
          API_KEY: ${{ secrets.TWITTER_API_KEY }}
          API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python3 tweet.py
      
      - name: Upload last_tweet_date artifact
        uses: actions/upload-artifact@v3
        with:
          name: last_tweet_date
          path: last_tweet_date.txt
```