on:
  workflow_dispatch:

jobs:
  post-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Upload last_tweet_date artifact
      - run: mkdir artifact
      - run: echo FEB 22, 2025 > artifact/last_tweet_date.txt
      - uses: actions/upload-artifact@v4
        with:
          name: last_tweet_date
          path: artifact/last_tweet_date.txt
